apiVersion: v1 
kind: ConfigMap 
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global: 
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'kubernetes-apiservers'
        kubernetes_sd_configs:
          - role: endpoints

      - job_name: 'backend'
        static_configs:
          - targets: ['backend:8000']
        
      - job_name: 'frontend'
        static_configs:
          - targets: ['frontend:8001']