pipeline{
    agent any
    
    environment{
        IMAGE_NAME= 'sharmaaakash170/cloud-native-backend'
        TAG = 'latest'
    }

    stages{
        stage('Build Docker Image'){
            steps{
                sh 'docker build -t $IMAGE_NAME:$TAG backend'
            }
        }

        stage('Push to Dockerhub'){
            steps{
                withCredentials([usernamePassword(credentialsId:'dockerhub-creds', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]){
                    sh """
                        echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                        docker push $IMAGE_NAME:$TAG
                        """
                }
            }
        }

        stage('Deploy Canary'){
            steps{
                sh 'kubectl set image deployment/backend backend=$IMAGE_NAME:$TAG'
            }
        }
    }
}